t4:
  通用:
    cateUuid: 17063            # 修改、新增商品、都用这个四级类   人造草坪
    accept1Uuid: 2100003050    # 测试验收事项1    数值型     固定两个验收事项，四级类绑定用，为防止他人修改，使用之前初始化一次
    accept2Uuid: 2100003051    # 测试验收事项2    文本型


