t4:
  host: ''

fangzhen:
  host: http://product.pre.xinfangsheng.com
  token: 479fff228f5d4b0c886e8fe4bd900833
  db_link: 127.0.0.1
  db_user: root
  db_pass: qwe123123
  db_database: productTestFrame